#!/bin/bash

BKUP_DIR=/opt/Embitude

if [ ! -f ${BKUP_DIR}/MLO ] || [ ! -f ${BKUP_DIR}/u-boot.img ]
then
	echo "No backup to restore. Run 'backup_bl' to take a backup first."
	exit 1
fi

UBOOT="u-boot.img"

cd ${BKUP_DIR}
BLK_CNT=1024

if (mountpoint -q /boot/uboot)
then
	cp -a MLO u-boot.img /boot/uboot
else
	if [ -f /opt/u-boot/bb-u-boot-am335x-evm ]
		UBOOT="u-boot-dtb.img"
		BLK_CNT=3072
	fi
	eMMC=/dev/$(ls /sys/bus/mmc/devices/mmc1*/block)

	dd if=${BKUP_DIR}/MLO of=${eMMC} bs=512 seek=256 count=256 conv=notrunc 2> /dev/null
	dd if=${BKUP_DIR}/${UBOOT} of=${eMMC} bs=512 seek=768 count=${BLK_CNT} conv=notrunc 2> /dev/null
fi
sync

if [ "$1" != "-q" ]
then
	echo "Restoring bootloader(s) successful."
	echo
	echo "*** Now, do a 'poweroff'. Then, remove the uSD (if inserted) and do a cold reboot. ***"
	echo
fi
